name: Paul Henderson
favicon: null
layout_spectrum: 0.6548372122924775
typography_spectrum: 0.9105823901481926
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.995983075350523
  lightness: 0.6443930047098547
  saturation: 0.008997790981084108
  rhythmicContrast: 0.4069362541195005
purpose: []
